# Generated by Django 4.2.3 on 2023-07-18 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Films',
            new_name='Film',
        ),
    ]
