# Generated by Django 4.2.3 on 2023-07-23 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_app', '0002_rename_films_film'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=250)),
                ('f_year', models.CharField(max_length=250)),
                ('f_genre', models.CharField(max_length=250)),
                ('f_prate', models.CharField(max_length=250)),
            ],
        ),
    ]
